// ANIGO Canonical Morph Slider Catalog across 18 Anatomical Zones (157 sliders)
// Autogenerated and synchronized with crates/anigo-core/src/morph_catalog.rs
// NOTE: the count is derived from CANONICAL_SLIDERS.length — never hardcode it.

export interface MorphSlider {
  id: string;
  name: string;
  zoneKey: string;
  min: number;
  defaultValue: number;
  max: number;
  step: number;
  dimorphism: "Both" | "MaleOnly" | "FemaleOnly";
}

export interface MorphZone {
  key: string;
  name: string;
  sliders: MorphSlider[];
}

export const CANONICAL_SLIDERS: MorphSlider[] = [
  {
    "id": "height_overall",
    "name": "Altura Estelar Total",
    "zoneKey": "GlobalSilhouette",
    "min": 1.1,
    "defaultValue": 1.65,
    "max": 2.15,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "head_to_body_ratio",
    "name": "Régua de Cabeças Canônica",
    "zoneKey": "GlobalSilhouette",
    "min": 2,
    "defaultValue": 6.5,
    "max": 8.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "head_scale_uniform",
    "name": "Escala do Crânio",
    "zoneKey": "GlobalSilhouette",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.6,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "torso_to_limb_ratio",
    "name": "Proporção Tronco/Pernas",
    "zoneKey": "GlobalSilhouette",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "somatotype_endomorph",
    "name": "Gordura / Corpulência Macro",
    "zoneKey": "GlobalSilhouette",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "somatotype_mesomorph",
    "name": "Musculatura / Atletismo Macro",
    "zoneKey": "GlobalSilhouette",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "somatotype_ectomorph",
    "name": "Magreza / Estrutura Óssea Macro",
    "zoneKey": "GlobalSilhouette",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "spine_s_curvature",
    "name": "Curvatura de Postura S-Line",
    "zoneKey": "GlobalSilhouette",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "head_width",
    "name": "Largura Biparietal",
    "zoneKey": "Craniofacial",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.35,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "head_depth",
    "name": "Profundidade Occipital",
    "zoneKey": "Craniofacial",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "face_lower_length",
    "name": "Altura do Terço Inferior",
    "zoneKey": "Craniofacial",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "forehead_height",
    "name": "Altura da Testa",
    "zoneKey": "Craniofacial",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "forehead_roundness",
    "name": "Curvatura Frontal",
    "zoneKey": "Craniofacial",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "brow_ridge_prominence",
    "name": "Arco Supraciliar",
    "zoneKey": "Craniofacial",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "temple_width",
    "name": "Largura das Têmporas",
    "zoneKey": "Craniofacial",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.25,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "cheekbone_prominence",
    "name": "Projeção Zigomática",
    "zoneKey": "Craniofacial",
    "min": 0,
    "defaultValue": 0.3,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "cheek_fullness_upper",
    "name": "Volume Malar Superior",
    "zoneKey": "Craniofacial",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "cheek_hollow_lower",
    "name": "Concavidade Bucal Inferior",
    "zoneKey": "Craniofacial",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "head_neck_blend",
    "name": "Transição Cabeça-Pescoço",
    "zoneKey": "Craniofacial",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eye_scale_uniform",
    "name": "Escala Geral dos Olhos",
    "zoneKey": "Eyes",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.6,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eye_horizontal_width",
    "name": "Largura Palpebral",
    "zoneKey": "Eyes",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eye_vertical_height",
    "name": "Abertura Vertical",
    "zoneKey": "Eyes",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eye_interpupillary_dist",
    "name": "Espaçamento Intercantal",
    "zoneKey": "Eyes",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eye_vertical_position",
    "name": "Posição Vertical na Face",
    "zoneKey": "Eyes",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eye_socket_depth",
    "name": "Profundidade Orbital",
    "zoneKey": "Eyes",
    "min": -0.5,
    "defaultValue": 0,
    "max": 0.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eye_canthal_tilt",
    "name": "Inclinação Cantal (Tsurime/Tareme)",
    "zoneKey": "Eyes",
    "min": -20,
    "defaultValue": 0,
    "max": 20,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "iris_scale_ratio",
    "name": "Proporção da Íris",
    "zoneKey": "Eyes",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "upper_eyelid_fold",
    "name": "Dobra Palpebral Superior",
    "zoneKey": "Eyes",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "lower_eyelid_aegyosal",
    "name": "Volume da Bolsa Aegyosal",
    "zoneKey": "Eyes",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eyelid_corner_curve",
    "name": "Curvatura dos Cantos",
    "zoneKey": "Eyes",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "pupil_vertical_squash",
    "name": "Formato Oval da Pupila",
    "zoneKey": "Eyes",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eyebrow_thickness",
    "name": "Espessura da Sobrancelha",
    "zoneKey": "Eyebrows",
    "min": 0.5,
    "defaultValue": 1,
    "max": 2,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eyebrow_arch_height",
    "name": "Altura do Arco Superior",
    "zoneKey": "Eyebrows",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eyebrow_inner_slant",
    "name": "Inclinação Medial",
    "zoneKey": "Eyebrows",
    "min": -15,
    "defaultValue": 0,
    "max": 15,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "eyebrow_spacing",
    "name": "Distância Glabelar",
    "zoneKey": "Eyebrows",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eyebrow_length",
    "name": "Comprimento Horizontal",
    "zoneKey": "Eyebrows",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "eyebrow_depth",
    "name": "Projeção em Relevo",
    "zoneKey": "Eyebrows",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "nose_bridge_height",
    "name": "Altura da Raiz Nasal",
    "zoneKey": "Nose",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "nose_bridge_depth",
    "name": "Projeção de Perfil do Dorso",
    "zoneKey": "Nose",
    "min": 0.5,
    "defaultValue": 1,
    "max": 1.6,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "nose_length_vertical",
    "name": "Comprimento Longitudinal",
    "zoneKey": "Nose",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "nose_tip_upturn",
    "name": "Ângulo da Ponta (Arrebitado)",
    "zoneKey": "Nose",
    "min": -25,
    "defaultValue": 0,
    "max": 25,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "nose_tip_sharpness",
    "name": "Afunilamento da Ponta",
    "zoneKey": "Nose",
    "min": 0,
    "defaultValue": 0.7,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "nose_alar_width",
    "name": "Largura da Base Alar",
    "zoneKey": "Nose",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "nose_nostril_visibility",
    "name": "Definição das Narinas",
    "zoneKey": "Nose",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "nose_profile_flatness",
    "name": "Achatamento Anime Muzzle",
    "zoneKey": "Nose",
    "min": 0,
    "defaultValue": 0.6,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "mouth_width",
    "name": "Largura da Rima Bucal",
    "zoneKey": "MouthLips",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "mouth_vertical_pos",
    "name": "Posição Vertical / Filtro",
    "zoneKey": "MouthLips",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "mouth_depth_protrusion",
    "name": "Projeção Dentofacial",
    "zoneKey": "MouthLips",
    "min": -0.5,
    "defaultValue": 0,
    "max": 0.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "lip_upper_thickness",
    "name": "Espessura do Lábio Superior",
    "zoneKey": "MouthLips",
    "min": 0.2,
    "defaultValue": 1,
    "max": 2,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "lip_lower_thickness",
    "name": "Espessura do Lábio Inferior",
    "zoneKey": "MouthLips",
    "min": 0.2,
    "defaultValue": 1,
    "max": 2,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "lip_corner_tilt",
    "name": "Curvatura de Comissura",
    "zoneKey": "MouthLips",
    "min": -15,
    "defaultValue": 0,
    "max": 15,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "lip_philtrum_depth",
    "name": "Profundidade do Filtro",
    "zoneKey": "MouthLips",
    "min": 0,
    "defaultValue": 0.3,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "mouth_tuck_depth",
    "name": "Reentrância das Comissuras",
    "zoneKey": "MouthLips",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "jaw_bigonial_width",
    "name": "Largura Bigoníaca da Mandíbula",
    "zoneKey": "JawChin",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.35,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "jaw_angle_vertical",
    "name": "Altura do Ramo da Mandíbula",
    "zoneKey": "JawChin",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.25,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "jaw_v_line_taper",
    "name": "Afunilamento V-Line Anime",
    "zoneKey": "JawChin",
    "min": 0,
    "defaultValue": 0.6,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "chin_length",
    "name": "Altura Vertical do Mento",
    "zoneKey": "JawChin",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "chin_width",
    "name": "Largura da Ponta do Queixo",
    "zoneKey": "JawChin",
    "min": 0.5,
    "defaultValue": 1,
    "max": 1.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "chin_forward_projection",
    "name": "Projeção do Pogônio",
    "zoneKey": "JawChin",
    "min": -0.5,
    "defaultValue": 0,
    "max": 0.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "chin_cleft_dimple",
    "name": "Covinha no Queixo (Cleft)",
    "zoneKey": "JawChin",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "MaleOnly"
  },
  {
    "id": "submental_fullness",
    "name": "Gordura Submentoniana (Papada)",
    "zoneKey": "JawChin",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "jawline_bone_definition",
    "name": "Nitidez da Borda Mandibular",
    "zoneKey": "JawChin",
    "min": 0,
    "defaultValue": 0.7,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "anime_profile_slant",
    "name": "Slant de Perfil Anime",
    "zoneKey": "JawChin",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "ear_scale_uniform",
    "name": "Escala Auricular Total",
    "zoneKey": "Ears",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "ear_flare_angle",
    "name": "Ângulo de Abertura (Orelha de Abano)",
    "zoneKey": "Ears",
    "min": 0,
    "defaultValue": 15,
    "max": 40,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "ear_pointy_elf",
    "name": "Ponta Élfica / Fantasia",
    "zoneKey": "Ears",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "ear_lobe_length",
    "name": "Comprimento do Lóbulo",
    "zoneKey": "Ears",
    "min": 0.5,
    "defaultValue": 1,
    "max": 1.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "ear_vertical_position",
    "name": "Posição Vertical na Cabeça",
    "zoneKey": "Ears",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "neck_length",
    "name": "Comprimento do Pescoço",
    "zoneKey": "NeckTrapezius",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.35,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "neck_circumference",
    "name": "Circunferência e Espessura",
    "zoneKey": "NeckTrapezius",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "trapezius_bulk",
    "name": "Volume Superior do Trapézio",
    "zoneKey": "NeckTrapezius",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "adams_apple_prominence",
    "name": "Pomo de Adão",
    "zoneKey": "NeckTrapezius",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "MaleOnly"
  },
  {
    "id": "scull_scm_tendon_relief",
    "name": "Músculo Esternocleidomastóideo",
    "zoneKey": "NeckTrapezius",
    "min": 0,
    "defaultValue": 0.3,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "throat_concavity",
    "name": "Concavidade da Fossa Jugular",
    "zoneKey": "NeckTrapezius",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "neck_forward_posture",
    "name": "Projeção Anterior do Pescoço",
    "zoneKey": "NeckTrapezius",
    "min": -15,
    "defaultValue": 0,
    "max": 20,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "shoulder_biacromial_width",
    "name": "Largura Biacromial dos Ombros",
    "zoneKey": "ShouldersClavicles",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "shoulder_acromial_slope",
    "name": "Inclinação Acromial",
    "zoneKey": "ShouldersClavicles",
    "min": -10,
    "defaultValue": 0,
    "max": 15,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "deltoid_muscle_volume",
    "name": "Volume do Deltoide",
    "zoneKey": "ShouldersClavicles",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "clavicle_bone_relief",
    "name": "Nitidez Óssea da Clavícula",
    "zoneKey": "ShouldersClavicles",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "clavicle_v_angle",
    "name": "Inclinação em V das Clavículas",
    "zoneKey": "ShouldersClavicles",
    "min": -10,
    "defaultValue": 0,
    "max": 15,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "scapula_wing_relief",
    "name": "Proeminência das Escápulas",
    "zoneKey": "ShouldersClavicles",
    "min": 0,
    "defaultValue": 0.3,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "shoulder_depth_thickness",
    "name": "Espessura Glenoumeral",
    "zoneKey": "ShouldersClavicles",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "latissimus_dorsi_flare",
    "name": "Expansão do Grande Dorsal",
    "zoneKey": "ShouldersClavicles",
    "min": 0,
    "defaultValue": 0.1,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "ribcage_width",
    "name": "Largura Torácica",
    "zoneKey": "ChestPectorals",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "ribcage_depth",
    "name": "Profundidade do Tórax",
    "zoneKey": "ChestPectorals",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "pectoral_muscle_bulk",
    "name": "Volume do Peitoral Maior",
    "zoneKey": "ChestPectorals",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "MaleOnly"
  },
  {
    "id": "pectoral_lower_cut",
    "name": "Definição da Linha Inframamária",
    "zoneKey": "ChestPectorals",
    "min": 0,
    "defaultValue": 0.4,
    "max": 1,
    "step": 0.01,
    "dimorphism": "MaleOnly"
  },
  {
    "id": "pectoral_sternal_cleave",
    "name": "Separação Esternal",
    "zoneKey": "ChestPectorals",
    "min": 0,
    "defaultValue": 0.3,
    "max": 1,
    "step": 0.01,
    "dimorphism": "MaleOnly"
  },
  {
    "id": "sternum_hollow_depth",
    "name": "Concavidade Esternal",
    "zoneKey": "ChestPectorals",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "bust_volume_cup",
    "name": "Volume do Busto (Copa A a G)",
    "zoneKey": "BustFemale",
    "min": 0,
    "defaultValue": 0.35,
    "max": 1.5,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "bust_vertical_position",
    "name": "Altura de Inserção Torácica",
    "zoneKey": "BustFemale",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "bust_separation_cleavage",
    "name": "Distância Intermamária (Decote)",
    "zoneKey": "BustFemale",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.5,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "bust_gravity_sag",
    "name": "Caimento em Gota / Gravidade",
    "zoneKey": "BustFemale",
    "min": 0,
    "defaultValue": 0.3,
    "max": 1,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "bust_firmness_roundness",
    "name": "Firmeza / Turgor Adiposo",
    "zoneKey": "BustFemale",
    "min": 0,
    "defaultValue": 0.7,
    "max": 1,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "bust_outward_angle",
    "name": "Ângulo de Divergência Lateral",
    "zoneKey": "BustFemale",
    "min": 0,
    "defaultValue": 10,
    "max": 25,
    "step": 1,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "bust_areola_diameter",
    "name": "Diâmetro da Aréola",
    "zoneKey": "BustFemale",
    "min": 0.5,
    "defaultValue": 1,
    "max": 2,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "bust_nipple_projection",
    "name": "Projeção da Papila Mamária",
    "zoneKey": "BustFemale",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "bust_underbust_taper",
    "name": "Afunilamento Submamário",
    "zoneKey": "BustFemale",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.25,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "waist_pinch_width",
    "name": "Estreitamento da Cintura",
    "zoneKey": "AbdomenWaist",
    "min": 0.65,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "waist_pinch_height",
    "name": "Altura do Pinch da Cintura",
    "zoneKey": "AbdomenWaist",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.2,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "belly_visceral_protuberance",
    "name": "Projeção Abdominal Anterior",
    "zoneKey": "AbdomenWaist",
    "min": -0.5,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "belly_lower_panniculus",
    "name": "Avental Adiposo Hipogástrico",
    "zoneKey": "AbdomenWaist",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "abs_sixpack_definition",
    "name": "Relevo do Reto Abdominal",
    "zoneKey": "AbdomenWaist",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "oblique_apollo_belt",
    "name": "Crista Ilíaca / Cinturão de Apolo",
    "zoneKey": "AbdomenWaist",
    "min": 0,
    "defaultValue": 0.1,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "flank_love_handles",
    "name": "Gordura nos Flancos Laterais",
    "zoneKey": "AbdomenWaist",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "ribcage_costal_margin",
    "name": "Projeção das Costelas Inferiores",
    "zoneKey": "AbdomenWaist",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "navel_vertical_pos",
    "name": "Posição Vertical do Umbigo",
    "zoneKey": "AbdomenWaist",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "navel_shape_slit",
    "name": "Formato em Fenda Vertical",
    "zoneKey": "AbdomenWaist",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "stomach_vacuum_depth",
    "name": "Sucção Abdominal (Vacuum)",
    "zoneKey": "AbdomenWaist",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "pelvis_bicristal_width",
    "name": "Largura Bicristal da Bacia",
    "zoneKey": "PelvisHips",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.35,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "hip_trochanteric_flare",
    "name": "Curvatura Bitrocantérica (Quadris)",
    "zoneKey": "PelvisHips",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.45,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "pelvic_tilt_angle",
    "name": "Anteversão / Retroversão Pélvica",
    "zoneKey": "PelvisHips",
    "min": -15,
    "defaultValue": 0,
    "max": 20,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "iliac_crest_prominence",
    "name": "Nitidez da Crista Ilíaca",
    "zoneKey": "PelvisHips",
    "min": 0,
    "defaultValue": 0.4,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "trochanteric_fat_saddlebag",
    "name": "Depósito de Culotes Laterais",
    "zoneKey": "PelvisHips",
    "min": 0,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "FemaleOnly"
  },
  {
    "id": "hip_dip_fill",
    "name": "Preenchimento do Hip Dip",
    "zoneKey": "PelvisHips",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "pubic_arch_width",
    "name": "Largura do Arco Púbico",
    "zoneKey": "PelvisHips",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "pelvis_depth",
    "name": "Profundidade da Bacia",
    "zoneKey": "PelvisHips",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "groin_crease_depth",
    "name": "Sulco da Dobra Inguinal",
    "zoneKey": "PelvisHips",
    "min": 0,
    "defaultValue": 0.4,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "gluteus_volume_overall",
    "name": "Volume Total das Nádegas",
    "zoneKey": "Gluteus",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.6,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "gluteus_posterior_shelf",
    "name": "Projeção Posterior de Perfil",
    "zoneKey": "Gluteus",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.6,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "gluteus_lift_height",
    "name": "Elevação Glútea Anti-Gravidade",
    "zoneKey": "Gluteus",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "gluteal_crease_depth",
    "name": "Profundidade da Prega Infraglútea",
    "zoneKey": "Gluteus",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "gluteus_shape_profile",
    "name": "Perfil Geométrico Glúteo",
    "zoneKey": "Gluteus",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "gluteus_medius_fill",
    "name": "Volume Súpero-Lateral",
    "zoneKey": "Gluteus",
    "min": 0,
    "defaultValue": 0.3,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "gluteus_firmness",
    "name": "Firmeza Muscular vs Flacidez",
    "zoneKey": "Gluteus",
    "min": 0,
    "defaultValue": 0.6,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "intergluteal_cleft_depth",
    "name": "Profundidade do Sulco Central",
    "zoneKey": "Gluteus",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "infragluteal_crease_length",
    "name": "Comprimento da Dobra Inferior",
    "zoneKey": "Gluteus",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "arm_length_overall",
    "name": "Comprimento Total do Braço",
    "zoneKey": "UpperLimbs",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "upper_arm_length",
    "name": "Comprimento do Úmero",
    "zoneKey": "UpperLimbs",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.25,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "forearm_length",
    "name": "Comprimento Rádio-Ulna",
    "zoneKey": "UpperLimbs",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.25,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "upper_arm_thickness",
    "name": "Espessura Geral do Braço",
    "zoneKey": "UpperLimbs",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.5,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "biceps_peak_volume",
    "name": "Pico do Bíceps Braquial",
    "zoneKey": "UpperLimbs",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "triceps_bulk",
    "name": "Massa do Tríceps Braquial",
    "zoneKey": "UpperLimbs",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "forearm_brachioradialis",
    "name": "Massa do Braquiorradial",
    "zoneKey": "UpperLimbs",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "forearm_taper_ratio",
    "name": "Razão de Afunilamento",
    "zoneKey": "UpperLimbs",
    "min": 0.6,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "elbow_olecranon_sharpness",
    "name": "Nitidez do Cotovelo (Olécrano)",
    "zoneKey": "UpperLimbs",
    "min": 0,
    "defaultValue": 0.4,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "wrist_circumference",
    "name": "Circunferência do Punho",
    "zoneKey": "UpperLimbs",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.35,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "hand_scale_uniform",
    "name": "Escala da Mão",
    "zoneKey": "HandsFingers",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.35,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "palm_width",
    "name": "Largura Metacarpal da Palma",
    "zoneKey": "HandsFingers",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.35,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "palm_length",
    "name": "Comprimento da Palma",
    "zoneKey": "HandsFingers",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.25,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "finger_length",
    "name": "Comprimento dos Dedos",
    "zoneKey": "HandsFingers",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "finger_thickness",
    "name": "Espessura das Falanges",
    "zoneKey": "HandsFingers",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "knuckle_joint_definition",
    "name": "Relevo dos Nós dos Dedos",
    "zoneKey": "HandsFingers",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "thumb_opposability_angle",
    "name": "Ângulo de Abertura do Polegar",
    "zoneKey": "HandsFingers",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "fingernail_style_anime",
    "name": "Formato das Unhas Anime",
    "zoneKey": "HandsFingers",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "leg_length_overall",
    "name": "Comprimento Total da Perna",
    "zoneKey": "LowerLimbs",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "thigh_length",
    "name": "Comprimento do Fêmur",
    "zoneKey": "LowerLimbs",
    "min": 0.8,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "thigh_circumference",
    "name": "Circunferência da Coxa",
    "zoneKey": "LowerLimbs",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.45,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "inner_thigh_gap",
    "name": "Espaçamento Adutor Medial",
    "zoneKey": "LowerLimbs",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "outer_thigh_sweep",
    "name": "Curvatura Lateral da Coxa",
    "zoneKey": "LowerLimbs",
    "min": 0,
    "defaultValue": 0.4,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "quadriceps_definition",
    "name": "Relevo do Reto Femoral/Vasto",
    "zoneKey": "LowerLimbs",
    "min": 0,
    "defaultValue": 0.2,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "knee_patella_prominence",
    "name": "Projeção Óssea da Patela",
    "zoneKey": "LowerLimbs",
    "min": 0,
    "defaultValue": 0.5,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "knee_valgus_uchimata",
    "name": "Alinhamento Valgo (Uchimata Anime)",
    "zoneKey": "LowerLimbs",
    "min": -10,
    "defaultValue": 0,
    "max": 15,
    "step": 1,
    "dimorphism": "Both"
  },
  {
    "id": "calf_circumference",
    "name": "Circunferência da Panturrilha",
    "zoneKey": "LowerLimbs",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.4,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "gastrocnemius_height",
    "name": "Altura do Ventre Muscular",
    "zoneKey": "LowerLimbs",
    "min": -1,
    "defaultValue": 0,
    "max": 1,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "ankle_malleolus_thickness",
    "name": "Espessura do Tornozelo",
    "zoneKey": "LowerLimbs",
    "min": 0.7,
    "defaultValue": 1,
    "max": 1.35,
    "step": 0.01,
    "dimorphism": "Both"
  },
  {
    "id": "foot_scale_and_arch",
    "name": "Tamanho do Pé e Arco Plantar",
    "zoneKey": "LowerLimbs",
    "min": 0.75,
    "defaultValue": 1,
    "max": 1.3,
    "step": 0.01,
    "dimorphism": "Both"
  }
];

export const CANONICAL_ZONES: MorphZone[] = [
  {
    "key": "GlobalSilhouette",
    "name": "Proporções Globais & Silhueta"
  },
  {
    "key": "Craniofacial",
    "name": "Crânio e Estrutura Craniofacial"
  },
  {
    "key": "Eyes",
    "name": "Olhos e Órbitas Anime"
  },
  {
    "key": "Eyebrows",
    "name": "Sobrancelhas Estruturais"
  },
  {
    "key": "Nose",
    "name": "Nariz Estilizado Anime"
  },
  {
    "key": "MouthLips",
    "name": "Boca e Lábios"
  },
  {
    "key": "JawChin",
    "name": "Mandíbula, Queixo e Linha V"
  },
  {
    "key": "Ears",
    "name": "Orelhas Anime/Élficas"
  },
  {
    "key": "NeckTrapezius",
    "name": "Pescoço, Trapézio e Pomo de Adão"
  },
  {
    "key": "ShouldersClavicles",
    "name": "Ombros, Clavículas e Grande Dorsal"
  },
  {
    "key": "ChestPectorals",
    "name": "Tórax e Peitorais Masculinos"
  },
  {
    "key": "BustFemale",
    "name": "Busto e Glândulas Mamárias Femininas"
  },
  {
    "key": "AbdomenWaist",
    "name": "Abdômen, Cintura e Flancos"
  },
  {
    "key": "PelvisHips",
    "name": "Pelve, Bacia e Curva do Quadril"
  },
  {
    "key": "Gluteus",
    "name": "Glúteos e Nádegas"
  },
  {
    "key": "UpperLimbs",
    "name": "Braços, Antebraços e Cotovelos"
  },
  {
    "key": "HandsFingers",
    "name": "Mãos e Dedos"
  },
  {
    "key": "LowerLimbs",
    "name": "Pernas, Joelhos, Panturrilhas e Pés"
  }
].map(z => ({
  ...z,
  sliders: CANONICAL_SLIDERS.filter(s => s.zoneKey === z.key)
}));
